<a href="https://colab.research.google.com/github/s-miramontes/News_Filter/blob/emma/Pilot/Data%20Cleanse%20and%20Clustering%20Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clustering News Headlines

In this notebook we begin my importing data to analyze its contents and be able to determine the best clustering algorithm to determine the articles that are mostly related to each other.

We start by importing some dependencies

In [1]:
import numpy as np
import pandas as pd

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

import re
from nltk.stem.snowball import SnowballStemmer

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.cluster import KMeans

from sklearn.metrics.pairwise import cosine_similarity

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/erusson/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [0]:
%%capture
# Install the latest Tensorflow version.
!pip3 install --upgrade tensorflow-gpu
# Install TF-Hub.
!pip3 install tensorflow-hub
!pip3 install seaborn

In [0]:
from absl import logging

import tensorflow as tf
import tensorflow_hub as hub

import os

import heapq
import operator

## Importing Data from Local File System

Datasets are located here: https://www.kaggle.com/snapcrack/all-the-news/version/4#articles3.csv

Proceed to download all three 'csv' files, and store them in a 'data' directory at the location of your choice.


*Note: It might be a better idea to have a way to import the data from the cloud (google drive) rather than from the user's local file system. Let's leave it like this for now, mainly bringing this up for easy reproducibility.*

Instead, we can mount google drive and import the datasets from an existing file in the cloud.

In [0]:
# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
# from google.colab import auth
# from oauth2client.client import GoogleCredentials

ModuleNotFoundError: ignored

In [0]:
# auth.authenticate_user()
# gauth = GoogleAuth()
# gauth.credentials = GoogleCredentials.get_application_default()
# drive = GoogleDrive(gauth)

For every file available we have a shared link:

CSV File: 'Articles 3':
https://drive.google.com/a/berkeley.edu/file/d/1BDhi5FuIvJ_6jiIdIFXRjT0w6tgfNk10/view?usp=sharing

CSV File: 'Articles 2':
https://drive.google.com/a/berkeley.edu/file/d/1qpoRkKEOnxYg_12e0RdeRi-JWUGWNFP3/view?usp=sharing

CSV File: 'Articles 1':
https://drive.google.com/a/berkeley.edu/file/d/1c9NbOIx7M6PgyJKxR9E7HgzuJlxGIaXU/view?usp=sharing


For each of the links above, we utiliz the File ID provided:

- Articles 1 File ID: '1BDhi5FuIvJ_6jiIdIFXRjT0w6tgfNk10'
- Articles 2 File ID: '1qpoRkKEOnxYg_12e0RdeRi-JWUGWNFP3'
- Articles 3 File ID: '1c9NbOIx7M6PgyJKxR9E7HgzuJlxGIaXU'


In [0]:
# downloaded3 = drive.CreateFile({'id':"1BDhi5FuIvJ_6jiIdIFXRjT0w6tgfNk10"})   # replace the id with id of file you want to access
# downloaded3.GetContentFile('articles3.csv.zip')        # replace the file name with your file

# downloaded2 = drive.CreateFile({'id': "1qpoRkKEOnxYg_12e0RdeRi-JWUGWNFP3"})
# downloaded2.GetContentFile('articles2.csv.zip')

# downloaded1 = drive.CreateFile({'id': "1c9NbOIx7M6PgyJKxR9E7HgzuJlxGIaXU"})
# downloaded1.GetContentFile('articles1.csv.zip')

In [0]:
articles_3 = pd.read_csv('w266/articles3.csv')
articles_2 = pd.read_csv('w266/articles2.csv')
articles_1 = pd.read_csv('w266/articles1.csv')

In [0]:
articles_3.head()

Unnamed: 0  ...                                            content
0      103459  ...  The son of a Louisiana man whose father was sh...
1      103460  ...  Copies of William Shakespeare’s first four boo...
2      103461  ...  Debt: $20, 000, Source: College, credit cards,...
3      103462  ...  It was late. I was drunk, nearing my 35th birt...
4      103463  ...  A central Texas man serving a life sentence fo...

[5 rows x 10 columns]

In [0]:
articles_2.head()

Unnamed: 0     id  ...  url                                            content
0       53293  73471  ...  NaN  Patriots Day, Peter Berg’s new thriller that r...
1       53294  73472  ...  NaN  In Norse mythology, humans and our world were ...
2       53295  73474  ...  NaN  “If our democracy is to work in this increasin...
3       53296  73475  ...  NaN  Updated on January 11 at 5:05 p. m. In his fir...
4       53297  73476  ...  NaN  Updated at 12:25 p. m. After months of equivoc...

[5 rows x 10 columns]

In [0]:
articles_1.head()

Unnamed: 0     id  ... url                                            content
0           0  17283  ... NaN  WASHINGTON  —   Congressional Republicans have...
1           1  17284  ... NaN  After the bullet shells get counted, the blood...
2           2  17285  ... NaN  When Walt Disney’s “Bambi” opened in 1942, cri...
3           3  17286  ... NaN  Death may be the great equalizer, but it isn’t...
4           4  17287  ... NaN  SEOUL, South Korea  —   North Korea’s leader, ...

[5 rows x 10 columns]

In [0]:
set(articles_3.publication)

{'Guardian', 'NPR', 'Reuters', 'Vox', 'Washington Post'}

In [0]:
set(articles_2.publication)

{'Atlantic',
 'Buzzfeed News',
 'Fox News',
 'Guardian',
 'National Review',
 'New York Post',
 'Talking Points Memo'}

In [0]:
set(articles_1.publication)

{'Atlantic', 'Breitbart', 'Business Insider', 'CNN', 'New York Times'}

In [0]:
full_data = pd.concat([articles_1, articles_2, articles_3], ignore_index=True)

In [5]:
full_data

Unnamed: 0      id                                              title  \
0                0   17283  House Republicans Fret About Winning Their Hea...   
1                1   17284  Rift Between Officers and Residents as Killing...   
2                2   17285  Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...   
3                3   17286  Among Deaths in 2016, a Heavy Toll in Pop Musi...   
4                4   17287  Kim Jong-un Says North Korea Is Preparing to T...   
...            ...     ...                                                ...   
142565      146028  218078  An eavesdropping Uber driver saved his 16-year...   
142566      146029  218079  Plane carrying six people returning from a Cav...   
142567      146030  218080  After helping a fraction of homeowners expecte...   
142568      146031  218081  Yes, this is real: Michigan just banned bannin...   
142569      146032  218082  What happened in Washington state after voters...   

            publication                         author        date    year  \
0        New York Times                     Carl Hulse  2016-12-31  2016.0   
1        New York Times  Benjamin Mueller and Al Baker  2017-06-19  2017.0   
2        New York Times                   Margalit Fox  2017-01-06  2017.0   
3        New York Times               William McDonald  2017-04-10  2017.0   
4        New York Times                  Choe Sang-Hun  2017-01-02  2017.0   
...                 ...                            ...         ...     ...   
142565  Washington Post                       Avi Selk  2016-12-30  2016.0   
142566  Washington Post                  Sarah Larimer  2016-12-30  2016.0   
142567  Washington Post                    Renae Merle  2016-12-30  2016.0   
142568  Washington Post                 Chelsea Harvey  2016-12-30  2016.0   
142569  Washington Post           Christopher Ingraham  2016-12-29  2016.0   

        month                                                url  \
0        12.0                                                NaN   
1         6.0                                                NaN   
2         1.0                                                NaN   
3         4.0                                                NaN   
4         1.0                                                NaN   
...       ...                                                ...   
142565   12.0  https://web.archive.org/web/20161231004909/htt...   
142566   12.0  https://web.archive.org/web/20161231004909/htt...   
142567   12.0  https://web.archive.org/web/20161231004909/htt...   
142568   12.0  https://web.archive.org/web/20161231004909/htt...   
142569   12.0  https://web.archive.org/web/20161231004909/htt...   

                                                  content  
0       WASHINGTON  —   Congressional Republicans have...  
1       After the bullet shells get counted, the blood...  
2       When Walt Disney’s “Bambi” opened in 1942, cri...  
3       Death may be the great equalizer, but it isn’t...  
4       SEOUL, South Korea  —   North Korea’s leader, ...  
...                                                   ...  
142565           Uber driver Keith Avila picked up a p...  
142566           Crews on Friday continued to search L...  
142567       When the Obama administration announced a...  
142568       This story has been updated. A new law in...  
142569       The nation’s first recreational marijuana...  

[142570 rows x 10 columns]

In [0]:
# remove duplicates
full_data = full_data.drop_duplicates(subset=['title', 'publication', 'author', 'date'])

In [0]:
# remove missing titles 
full_data = full_data.dropna(subset=['title'])

In [8]:
# sample from full_data (set seed to 5)
small_data = full_data.sample(n=10000, random_state=5).reset_index()
set(small_data.publication)

{'Atlantic',
 'Breitbart',
 'Business Insider',
 'Buzzfeed News',
 'CNN',
 'Fox News',
 'Guardian',
 'NPR',
 'National Review',
 'New York Post',
 'New York Times',
 'Reuters',
 'Talking Points Memo',
 'Vox',
 'Washington Post'}

In [9]:
small_data

index  Unnamed: 0      id  \
0      74496       77946  118473   
1      71184       74592  113594   
2     120205      123668  184574   
3     128977      132440  199665   
4     134837      138300  208223   
...      ...         ...     ...   
9995  137105      140568  211140   
9996   60293       63612   86308   
9997   55079       58389   80070   
9998  110248      113711  168509   
9999  123649      127112  190014   

                                                  title      publication  \
0     Chaos in the Family, Chaos in the State: The W...  National Review   
1      US Civil Rights Commission Will Observe Stand...    Buzzfeed News   
2     Venezuela hunts rogue helicopter attackers, Ma...          Reuters   
3     Fruit juice isn’t much better for you than sod...              Vox   
4     Sessions won’t testify at congressional budget...  Washington Post   
...                                                 ...              ...   
9995  Patient secretly recorded doctors as they oper...  Washington Post   
9996  Fox News Poll: Clinton edges Trump by two poin...         Fox News   
9997  The Atlantic  Politics & Policy Daily: Trump’s...         Atlantic   
9998  A Son In Chains. A Depressed Mom. Here’s What ...              NPR   
9999  Trump’s expected VP pick: coal advocate who de...          Reuters   

                                     author        date    year  month  \
0                       Kevin D. Williamson  2016-03-17  2016.0    3.0   
1                          Nidhi Subbaraman  2016-12-08  2016.0   12.0   
2     Andrew Cawthorne and Victoria Ramirez  2017-06-29  2017.0    6.0   
3                              Julia Belluz   2016/3/25  2016.0    3.0   
4                              Sari Horwitz  2017-06-10  2017.0    6.0   
...                                     ...         ...     ...    ...   
9995                             Yanan Wang  2016-04-07  2016.0    4.0   
9996                           Dana Blanton  2016-10-07  2016.0   10.0   
9997                         Elaine Godfrey  2016-08-31  2016.0    8.0   
9998                        Nurith Aizenman  2016-04-15  2016.0    4.0   
9999      Valerie Volcovici and Grant Smith  2016-07-15  2016.0    7.0   

                                                    url  \
0     http://www.nationalreview.com/article/432876/d...   
1     https://web.archive.org/web/20161208153906/htt...   
2     http://www.reuters.com/article/us-venezuela-po...   
3     http://www.vox.com/2016/3/25/11305614/soda-jui...   
4     https://web.archive.org/web/20170611000758/htt...   
...                                                 ...   
9995  https://web.archive.org/web/20160408000201/htt...   
9996  https://web.archive.org/web/20161008002456/htt...   
9997                                                NaN   
9998  http://www.npr.org/sections/goatsandsoda/2016/...   
9999  http://www.reuters.com/article/us-usa-election...   

                                                content  
0     Michael Brendan Dougherty is bitter. I think t...  
1      WASHINGTON  —   The US Commission on Civil Ri...  
2      The Venezuelan government hunted on Wednesday...  
3      One of the biggest public health wins of rece...  
4      Attorney General Jeff Sessions, who had agree...  
...                                                 ...  
9995         Last summer, Ethel Easter wanted nothin...  
9996  Third party candidates Gary Johnson (6 percent...  
9997          For us to continue writing great stori...  
9998  It was a hospital  —   but to psychologist Ink...  
9999   Republican Donald Trump’s selection of Indian...  

[10000 rows x 11 columns]

In [10]:
# remove publisher tags from article titles 

just_titles = []

for title in small_data.title:
  title = re.sub(r"(- Breitbart)(?!.*\1)", '', title)
  title = re.sub(r'(- The New York Times)(?!.*\1)', '', title)
  just_titles.append(title)

just_titles[:5]

['Chaos in the Family, Chaos in the State: The White Working Class’s Dysfunction',
 ' US Civil Rights Commission Will Observe Standing Rock\xa0Standoff',
 'Venezuela hunts rogue helicopter attackers, Maduro foes suspicious',
 'Fruit juice isn’t much better for you than soda. Let’s stop pretending otherwise.',
 'Sessions won’t testify at congressional budget hearings but at Senate intelligence hearing instead']

In [11]:
len(just_titles)

10000

In [12]:
# join with content of article

small_text = list(map(lambda i,j: i + " " + j, just_titles, small_data.content))

small_text[:5]

['Chaos in the Family, Chaos in the State: The White Working Class’s Dysfunction Michael Brendan Dougherty is bitter. I think that I can write that in both truth and charity. (I think you might even say that he and I are friends.) Dougherty is a conservative of the sort sometimes advertised as “paleo” and served as national correspondent for The American Conservative. Like many conservative writers with those associations, Dougherty spends a great deal of time lambasting the conservative movement and its organs, from which he feels, for whatever reason, estranged  —   an alienation that carries with it more than a little to suggest that it is somewhat personal. You know: Them. Donald Trump is the headline, and explaining the benighted white working class to Them is the main matter. Sanctimony is the literary mode, for Dougherty and for many others doing the same work with less literary facility. Never mind the petty sneering (as though the conservative movement were populated by septua

In [13]:
len(small_text)

10000

## Create Matrix of TF-IDF Features

In [0]:
def preprocess_text(text):

  # function to remove punctuation 
  def Punctuation(string): 
    return re.sub(r'[\W_]', ' ', string)

  # remove punctuation and perform tokenization
  text = Punctuation(text.lower()).split()

  # remove stop words and stem
  stop_words = set(stopwords.words('english'))
  stemmer = SnowballStemmer("english")
  text = [stemmer.stem(t) for t in text if not t in stop_words]

  return text


In [0]:
# tfidf vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=5000, stop_words='english', use_idf=True, tokenizer=preprocess_text, ngram_range=(1,3))

In [0]:
# fit just_titles to vectorizer
tfidf_matrix = tfidf_vectorizer.fit_transform(small_text)
print(tfidf_matrix.shape)

/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['afterward', 'alon', 'alreadi', 'alway', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becom', 'besid', 'cri', 'describ', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'forti', 'henc', 'hereaft', 'herebi', 'howev', 'hundr', 'inde', 'mani', 'meanwhil', 'moreov', 'nobodi', 'noon', 'noth', 'nowher', 'otherwis', 'perhap', 'pleas', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'thenc', 'thereaft', 'therebi', 'therefor', 'togeth', 'twelv', 'twenti', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


(10000, 5000)


In [0]:
# reduce memory 
tfidf_matrix = tfidf_matrix.astype(np.float32)

In [0]:
tfidf_matrix

<10000x5000 sparse matrix of type '<class 'numpy.float32'>'
	with 2077663 stored elements in Compressed Sparse Row format>

## Create Matrix of Word2Vec Features

## Universal Encoder

In [0]:
# load the Universal Sentence Encoder's TF Hub module

# module_url = "https://tfhub.dev/google/universal-sentence-encoder/4" #param ["https://tfhub.dev/google/universal-sentence-encoder/4", "https://tfhub.dev/google/universal-sentence-encoder-large/5"]
# model = hub.load(module_url)
# print ("module %s loaded" % module_url)

model = hub.load("w266/tmp")


In [0]:
# reduce logging output
logging.set_verbosity(logging.ERROR)

# compute a representation for each message
message_embeddings = model(small_text)

In [0]:
# semantic similarity of two sentences can be trivially computed as the inner product of the encodings
corr = np.inner(message_embeddings, message_embeddings)

In [17]:
# data frame of titles and semantic similarities
corr_df = pd.DataFrame(corr)
corr_df.columns = just_titles
corr_df.index = just_titles

corr_df.head()

Chaos in the Family, Chaos in the State: The White Working Class’s Dysfunction  \
Chaos in the Family, Chaos in the State: The Wh...                                           1.000000                                
 US Civil Rights Commission Will Observe Standi...                                           0.291457                                
Venezuela hunts rogue helicopter attackers, Mad...                                           0.336936                                
Fruit juice isn’t much better for you than soda...                                           0.256971                                
Sessions won’t testify at congressional budget ...                                           0.181461                                

                                                     US Civil Rights Commission Will Observe Standing Rock Standoff  \
Chaos in the Family, Chaos in the State: The Wh...                                           0.291457                 
 US Civil Rights Commission Will Observe Standi...                                           1.000000                 
Venezuela hunts rogue helicopter attackers, Mad...                                           0.543982                 
Fruit juice isn’t much better for you than soda...                                           0.109070                 
Sessions won’t testify at congressional budget ...                                           0.411541                 

                                                    Venezuela hunts rogue helicopter attackers, Maduro foes suspicious  \
Chaos in the Family, Chaos in the State: The Wh...                                           0.336936                    
 US Civil Rights Commission Will Observe Standi...                                           0.543982                    
Venezuela hunts rogue helicopter attackers, Mad...                                           1.000000                    
Fruit juice isn’t much better for you than soda...                                           0.106961                    
Sessions won’t testify at congressional budget ...                                           0.405647                    

                                                    Fruit juice isn’t much better for you than soda. Let’s stop pretending otherwise.  \
Chaos in the Family, Chaos in the State: The Wh...                                           0.256971                                   
 US Civil Rights Commission Will Observe Standi...                                           0.109070                                   
Venezuela hunts rogue helicopter attackers, Mad...                                           0.106961                                   
Fruit juice isn’t much better for you than soda...                                           1.000000                                   
Sessions won’t testify at congressional budget ...                                           0.052951                                   

                                                    Sessions won’t testify at congressional budget hearings but at Senate intelligence hearing instead  \
Chaos in the Family, Chaos in the State: The Wh...                                           0.181461                                                    
 US Civil Rights Commission Will Observe Standi...                                           0.411541                                                    
Venezuela hunts rogue helicopter attackers, Mad...                                           0.405647                                                    
Fruit juice isn’t much better for you than soda...                                           0.052951                                                    
Sessions won’t testify at congressional budget ...                                           1.000000                                                    

                                                   

In [18]:
# find index of 5 most similar titles 
top5_ind = [] 
for i in range(len(corr_df)):
  top5_ind.append(list(list(zip(*heapq.nlargest(5, enumerate(corr_df.iloc[i,:]), key=operator.itemgetter(1))))[0]))

# show most similar titles -- sanity check
top5 = []
for ind in top5_ind:
  top5.append([just_titles[i] for i in ind])

top5[:5]

[['Chaos in the Family, Chaos in the State: The White Working Class’s Dysfunction',
  'After Trump, conservatives should stop longing for the past — and learn a little humility',
  'The alt-right is more than warmed-over white supremacy. It’s that, but way way weirder.',
  'The Return of ‘Street Corner Conservatism’',
  'Liberals should get behind marriage (Opinion)'],
 [' US Civil Rights Commission Will Observe Standing Rock\xa0Standoff',
  ' Cory Booker Calls For Federal Investigation Into Police Tactics At Dakota Access\xa0Pipeline',
  'Army will close Dakota pipeline protesters’ campsite, Sioux leader\xa0says',
  'Dakota Access Pipeline protest site is cleared',
  'Protesters, Police Still Clashing Over Disputed North Dakota Pipeline'],
 ['Venezuela hunts rogue helicopter attackers, Maduro foes suspicious',
  'Protester dies, minister sacked after Paraguay re-election vote',
  'Venezuela Erupts In ’Mother Of All Protests’ As Anti-Maduro Sentiment Seethes',
  'Confusion In Venezuela

In [0]:
np.array(message_embeddings).shape

(1000, 512)

In [0]:
message_embeddings

<tf.Tensor: shape=(1000, 512), dtype=float32, numpy=
array([[ 0.01333818, -0.05380408,  0.00232677, ...,  0.0533301 ,
        -0.03825486,  0.04241087],
       [-0.01210087, -0.01844358,  0.05187282, ...,  0.05565305,
        -0.05972204,  0.04307982],
       [-0.00471127, -0.04964766, -0.05074216, ...,  0.05359754,
        -0.05339101, -0.05365704],
       ...,
       [ 0.00479301,  0.04639916, -0.04595203, ...,  0.0533572 ,
        -0.05650016,  0.02762916],
       [-0.04229458, -0.06001651,  0.03259774, ...,  0.03309052,
        -0.04628655,  0.05280183],
       [ 0.04829948, -0.05886184, -0.01870255, ...,  0.05115974,
        -0.0572932 ,  0.05578536]], dtype=float32)>

In [0]:
 km.cluster_centers_.shape


NameError: ignored

## Run KMeans Clustering 

In [0]:
num_clusters = 25

km = KMeans(n_clusters=num_clusters, random_state=10)

#km.fit(tfidf_matrix)
km.fit(message_embeddings)

clusters = km.labels_.tolist()

In [0]:
# cosine similarities for each row with cluster center
#cos_sim = [cosine_similarity(tfidf_matrix[i].toarray(), km.cluster_centers_[label].reshape(1, -1))[0][0] for i,label in enumerate(km.labels_)]
cos_sim = [cosine_similarity(np.array(message_embeddings[i]).reshape(1, -1), km.cluster_centers_[label].reshape(1, -1))[0][0] for i,label in enumerate(km.labels_)]
#sem_sim = [np.inner(np.array(message_embeddings[i]).reshape(1, -1), km.cluster_centers_[label].reshape(1, -1))[0][0] for i,label in enumerate(km.labels_)]


In [21]:
# sum of squared distances of samples to their closest cluster center.
km.inertia_

5733.306836503798

In [0]:
# simple dataframe with title, cluster, and cosine similarity 
title_data = pd.DataFrame({'title':small_data.title, 'cluster':clusters, 'cos_sim':cos_sim})

In [24]:
title_data

title  cluster   cos_sim
0     Chaos in the Family, Chaos in the State: The W...        3  0.649303
1      US Civil Rights Commission Will Observe Stand...        3  0.629662
2     Venezuela hunts rogue helicopter attackers, Ma...       10  0.683993
3     Fruit juice isn’t much better for you than sod...        1  0.408172
4     Sessions won’t testify at congressional budget...        5  0.760302
...                                                 ...      ...       ...
9995  Patient secretly recorded doctors as they oper...       11  0.566854
9996  Fox News Poll: Clinton edges Trump by two poin...       19  0.718047
9997  The Atlantic  Politics & Policy Daily: Trump’s...       22  0.777570
9998  A Son In Chains. A Depressed Mom. Here’s What ...       11  0.621257
9999  Trump’s expected VP pick: coal advocate who de...       20  0.715449

[10000 rows x 3 columns]

In [25]:
# inspect titles with highest cosine similarity in clusters 
top_5 = title_data.groupby('cluster')['cos_sim'].nlargest(5)
for i,ind in top_5.index:
  print("cluster", i)
  print(just_titles[ind])
  print('-------------')

cluster 0
23 killed in West Virginia floods that swept preschooler away from grandfather’s reach
-------------
cluster 0
At least 26 dead in West Virginia flooding
-------------
cluster 0
As floods threaten N.C., officials urge: ‘Move to higher ground now’
-------------
cluster 0
More than 280 reported dead in Haiti as extent of Hurricane Matthew damage comes into focus
-------------
cluster 0
Lake Oroville dam: emergency staff race to fix spillway before more rain strikes
-------------
cluster 1
Routine DNA Sequencing May Be Helpful And Not As Scary As Feared
-------------
cluster 1
’Minibrains’ Could Help Drug Discovery For Zika And For Alzheimer’s 
-------------
cluster 1
 At Gene Editing Meeting, Scientists Discuss God, Racism, Designer Babies
-------------
cluster 1
Can Web Search Predict Cancer? Promise And Worry Of Big Data And Health
-------------
cluster 1
Debunking the Debunkers on Sugar
-------------
cluster 2
House Republicans repeal Obamacare, hurdles await in U.S. Senate


In [26]:
top_5

cluster      
0        7054    0.782964
         7073    0.779029
         3178    0.766450
         6440    0.757836
         24      0.736117
                   ...   
24       3765    0.753378
         6195    0.740042
         3141    0.730567
         4448    0.719834
         7532    0.718625
Name: cos_sim, Length: 125, dtype: float64

## Predict Input

In [0]:
input_topic = ["Hillary Clinton defends handling of Benghazi attack", "Women's March Highlights", "Hillary Clinton emails"]

In [0]:
# run tfidf on input 
#tfidf_input = tfidf_vectorizer.transform(input_topic)

# make list of tfidf_input
#tfidf_input = [tfidf_input.getrow(i).toarray()[0].tolist() for i in range(tfidf_input.shape[0])]

In [0]:
# run encoder on input 
enc_input = model(input_topic)

# make list of enc_input
enc_input = [list(np.array(enc_input)[i]) for i in range(enc_input.shape[0])]

In [0]:
# make list of tfidf_matrix
#tfidf_list = [tfidf_matrix.getrow(i).toarray()[0].tolist() for i in range(tfidf_matrix.shape[0])]


In [0]:
# make list of message_embeddings
enc_list = [list(np.array(message_embeddings)[i]) for i in range(message_embeddings.shape[0])]


In [30]:
len(title_data.cluster)

10000

In [0]:
# np.random.seed(5)
# X_train = tfidf_list
# y_train = title_data.cluster
# X_test  = tfidf_input

# # Create and fit a nearest-neighbor classifier
# from sklearn.neighbors import KNeighborsClassifier
# knn = KNeighborsClassifier()
# knn.fit(X_train, y_train) 

# res = knn.predict(X_test)

In [0]:
np.random.seed(5)
X_train = enc_list
y_train = title_data.cluster
X_test  = enc_input

# Create and fit a nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train) 

res = knn.predict(X_test)

In [32]:
print(res)

[5 3 5]


In [34]:
for i,ind in top_5.index:
  if (i==3) | (i==5):
    print("cluster", i)
    print(just_titles[ind])
    print('-------------')

# ["Hillary Clinton defends handling of Benghazi attack", "Women's March Highlights", "Hillary Clinton emails"]

cluster 3
Milo Yiannopoulos is trying to convince colleges that hate speech is cool
-------------
cluster 3
Trump fans’ ’Deploraball’ party shows rift in alt-right movement
-------------
cluster 3
Yes, there is a free speech crisis. But its victims are not white men
-------------
cluster 3
Hate speech seeps into U.S. mainstream amid bitter campaign
-------------
cluster 3
Ciccotta: Guest Speaker’s Call to Violence Reveals Bucknell’s Radicalism 
-------------
cluster 5
Trump knows the feds are closing in on him
-------------
cluster 5
Comey to be pressed on whether Trump interfered with Russia probe
-------------
cluster 5
The FBI probe into Trump and Russia is huge news. Our political system isn’t ready for it.
-------------
cluster 5
Senate intelligence committee to question Trump team on links with Russia
-------------
cluster 5
Trump finds himself exactly where he doesn’t want to be
-------------


Check to see if individual vs mass inputs create different embeddings -- NO

In [0]:
a = model(["hi my name is emma"])
b = model(["nice to meet you"])
c = model(["hi what's your name"])

In [0]:
d = model(["hi my name is emma", "nice to meet you", "hi what's your name"])

In [0]:
e = np.concatenate((a, b, c))

In [0]:
f = np.array(d)

In [54]:
np.inner(e, e)

array([[1.        , 0.23792592, 0.5253966 ],
       [0.23792592, 1.        , 0.43527788],
       [0.5253966 , 0.43527788, 1.        ]], dtype=float32)

In [55]:
np.inner(f, f)

array([[0.9999999 , 0.23792589, 0.5253966 ],
       [0.23792589, 1.        , 0.43527794],
       [0.5253966 , 0.43527794, 1.0000001 ]], dtype=float32)

In [57]:
message_embeddings

<tf.Tensor: shape=(10000, 512), dtype=float32, numpy=
array([[ 0.01333818, -0.05380408,  0.00232677, ...,  0.0533301 ,
        -0.03825486,  0.04241087],
       [-0.01210087, -0.01844358,  0.05187282, ...,  0.05565305,
        -0.05972204,  0.04307982],
       [-0.00471127, -0.04964766, -0.05074216, ...,  0.05359754,
        -0.05339101, -0.05365704],
       ...,
       [-0.03098017, -0.05402634, -0.04946342, ...,  0.05646259,
        -0.05528343, -0.04850345],
       [ 0.0071629 , -0.05772226,  0.05848116, ...,  0.05804956,
        -0.05633788, -0.05588677],
       [ 0.03915349, -0.0549503 , -0.05372609, ...,  0.05495479,
        -0.05285954,  0.03810295]], dtype=float32)>

In [0]:
input_embeddings = model(input_topic)

In [59]:
input_embeddings

<tf.Tensor: shape=(3, 512), dtype=float32, numpy=
array([[-0.00043203,  0.03228568, -0.04395936, ...,  0.06762028,
        -0.03446475,  0.00829037],
       [-0.04381321,  0.0106896 ,  0.00313417, ...,  0.02813102,
        -0.07244141,  0.02743991],
       [ 0.00777211,  0.04472262,  0.00644468, ...,  0.03325547,
        -0.0335868 ,  0.00524749]], dtype=float32)>

In [0]:
inp_corr = np.inner(input_embeddings, message_embeddings)

In [64]:
# data frame of titles and semantic similarities
inp_df = pd.DataFrame(inp_corr)
inp_df.columns = just_titles
inp_df.index = input_topic

inp_df

Chaos in the Family, Chaos in the State: The White Working Class’s Dysfunction  \
Hillary Clinton defends handling of Benghazi at...                                           0.019261                                
Women's March Highlights                                                                     0.045296                                
Hillary Clinton emails                                                                       0.036642                                

                                                     US Civil Rights Commission Will Observe Standing Rock Standoff  \
Hillary Clinton defends handling of Benghazi at...                                           0.135737                 
Women's March Highlights                                                                     0.119294                 
Hillary Clinton emails                                                                       0.032883                 

                                                    Venezuela hunts rogue helicopter attackers, Maduro foes suspicious  \
Hillary Clinton defends handling of Benghazi at...                                           0.213940                    
Women's March Highlights                                                                    -0.000519                    
Hillary Clinton emails                                                                       0.058746                    

                                                    Fruit juice isn’t much better for you than soda. Let’s stop pretending otherwise.  \
Hillary Clinton defends handling of Benghazi at...                                          -0.040233                                   
Women's March Highlights                                                                     0.065587                                   
Hillary Clinton emails                                                                       0.017771                                   

                                                    Sessions won’t testify at congressional budget hearings but at Senate intelligence hearing instead  \
Hillary Clinton defends handling of Benghazi at...                                           0.270479                                                    
Women's March Highlights                                                                     0.049757                                                    
Hillary Clinton emails                                                                       0.199208                                                    

                                                    Qatar: UAE and Saudi Arabia step up pressure in diplomatic crisis  \
Hillary Clinton defends handling of Benghazi at...                                           0.242178                   
Women's March Highlights                                                                    -0.028455                   
Hillary Clinton emails                                                                       0.109163                   

                                                    ’The 4-Hour Workweek’ author says a 3-step process he learned from Tony Robbins drastically improved his life  \
Hillary Clinton defends handling of Benghazi at...                                          -0.059264                                                               
Women's March Highlights                                                                    -0.019417                                                               
Hillary Clinton emails                                                                      -0.048110                                                               

                                                    Rick Perry Attacked for Keeping His Word  \
Hillary Clinton defends handling of Benghazi at...                                  0.235375   
Women's March Highlights                     

In [65]:
# find index of 5 most similar titles 
top5_ind = [] 
for i in range(len(inp_df)):
  top5_ind.append(list(list(zip(*heapq.nlargest(5, enumerate(inp_df.iloc[i,:]), key=operator.itemgetter(1))))[0]))

# show most similar titles -- sanity check
top5 = []
for ind in top5_ind:
  top5.append([just_titles[i] for i in ind])

top5[:5]
# ["Hillary Clinton defends handling of Benghazi attack", "Women's March Highlights", "Hillary Clinton emails"]

[['Benghazi may be over, but #Benghazi has a life of its own',
  'The GOP stoops for scandal',
  'Exclusive - Sarah Palin: Administration Lies, Soldiers Die. Yes, Hillary, at Every Point ‘It Matters’ ',
  'Read the House Benghazi report',
  'Clinton Bristles at Question on E-mail Indictment: ‘It’s Not Going to Happen’'],
 ['The Women’s March on Washington is becoming a\xa0joke',
  ' Women Share Why They Hit The Streets At The Sundance Women’s\xa0March',
  'Women will march on – What would a feminist do? podcast',
  'The Exhausting Work of Tallying America’s Largest Protest',
  'Women’s March organizers prepare for hundreds of thousands of protesters'],
 ['Donald Trump: ’Good Job, Huma. Thank you, Anthony Weiner’ ',
  'Fox News anchor grills Hillary Clinton on her email scandal',
  'Hillary Clinton’s email problems might be even worse than we thought',
  'Hillary Clinton pal Neera Tanden’s greatest hits from WikiLeaks emails',
  'Hillary Clinton Deleted More Emails Than She Sent to the 